<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE TEI [
    <!ELEMENT TEI (header, facsimile?, testo+)>

    <!ELEMENT header (#PCDATA)>
    <!ATTLIST header
        type CDATA #FIXED "intestazione"
        lang NMTOKEN #IMPLIED>

    <!ELEMENT facsimile (#PCDATA)>
    <!ATTLIST facsimile
        source CDATA #REQUIRED
        ref IDREFS #IMPLIED>

    <!ELEMENT testo (#PCDATA | seg)*>
    <!ATTLIST testo
        id ID #REQUIRED
        type CDATA #IMPLIED>

    <!ELEMENT seg (#PCDATA)>
]>

<TEI>
    <header lang="it">Intestazione esercizio 7</header>

    <facsimile source="immagine.jpg">scansione</facsimile>

    <testo id="t1" type="introduzione">
        Questo è un <seg>segmento</seg> di testo.
    </testo>
</TEI>